export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
}

export const products: Product[] = [
  {
    id: "1",
    name: "Propeller (Small)",
    description: "Lightweight propeller for drones and small aerial robots.",
    price: 250,
    image: "/products/propeller-small.jpg",
    category: "Drone Parts",
  },
  {
    id: "2",
    name: "HC-05 Bluetooth Module",
    description: "Wireless Bluetooth serial module for Arduino and microcontroller projects.",
    price: 100,
    image: "/products/hc05.jpg",
    category: "Modules",
  },
  {
    id: "3",
    name: "ESP32 Development Board",
    description: "Wi-Fi & Bluetooth enabled microcontroller. Perfect for IoT and robotics.",
    price: 350,
    image: "/products/esp32.jpg",
    category: "Microcontrollers",
  },
  {
    id: "4",
    name: "BO Motor",
    description: "Compact DC geared motor for small robots and RC cars.",
    price: 100,
    image: "/products/bo-motor.jpg",
    category: "Motors",
  },
  {
    id: "5",
    name: "Propeller (Large)",
    description: "Heavy-duty HD propellers for larger drones and aerial platforms.",
    price: 500,
    image: "/products/propeller-large.jpg",
    category: "Drone Parts",
  },
  {
    id: "6",
    name: "Coil 5mm",
    description: "5mm copper coil for electromagnet and motor winding projects.",
    price: 350,
    image: "/products/coil.jpg",
    category: "Components",
  },
  {
    id: "7",
    name: "Ultrasonic Sensor HC-SR04",
    description: "Distance measuring sensor for obstacle avoidance. Range: 2cm to 400cm.",
    price: 100,
    image: "/products/ultrasonic.jpg",
    category: "Sensors",
  },
  {
    id: "8",
    name: "Joystick Module",
    description: "Analog joystick for remote control and robot navigation.",
    price: 100,
    image: "/products/joystick.jpg",
    category: "Modules",
  },
  {
    id: "9",
    name: "Bot ESP32 Kit",
    description: "Complete ESP32-based robot kit with motors, sensors, and chassis.",
    price: 2000,
    image: "/products/bot-esp32.jpg",
    category: "Kits",
  },
  {
    id: "10",
    name: "Charging Module / Buck Converter",
    description: "Step-down voltage converter for efficient battery charging and power regulation.",
    price: 100,
    image: "/products/charging-module.jpg",
    category: "Power",
  },
  {
    id: "11",
    name: "Drone",
    description: "Ready-to-fly drone with camera mount and GPS capabilities.",
    price: 30000,
    image: "/products/drone.jpg",
    category: "Drone Parts",
  },
  {
    id: "12",
    name: "Breadboard",
    description: "Solderless breadboard for prototyping electronic circuits.",
    price: 100,
    image: "/products/breadboard.jpg",
    category: "Components",
  },
  {
    id: "13",
    name: "Jumper Wires (10 pcs)",
    description: "Male-to-male jumper wires for breadboard connections.",
    price: 20,
    image: "/products/jumper-wires.jpg",
    category: "Components",
  },
  {
    id: "14",
    name: "4-Channel Relay Module",
    description: "Control high-voltage devices with your microcontroller safely.",
    price: 400,
    image: "/products/4ch-relay.jpg",
    category: "Modules",
  },
  {
    id: "15",
    name: "Duct Tape",
    description: "Heavy-duty adhesive tape for robot assembly and repairs.",
    price: 400,
    image: "/products/duct-tape.jpg",
    category: "Tools",
  },
  {
    id: "16",
    name: "20x4 LCD Display with I2C",
    description: "Large character LCD display with I2C interface for easy wiring.",
    price: 300,
    image: "/products/lcd-i2c.jpg",
    category: "Modules",
  },
  {
    id: "17",
    name: "L298N Motor Driver",
    description: "Dual H-bridge motor driver for controlling DC motors and stepper motors.",
    price: 200,
    image: "/products/l298n.jpg",
    category: "Motors",
  },
  {
    id: "18",
    name: "300 RPM Grade A High Torque 555 Motor",
    description: "High-torque DC motor rated at 300 RPM. Great for combat and heavy bots.",
    price: 500,
    image: "/products/555-motor.jpg",
    category: "Motors",
  },
  {
    id: "19",
    name: "BTS7960 Motor Driver",
    description: "High-current 43A motor driver for powerful DC motors.",
    price: 350,
    image: "/products/bts7960.jpg",
    category: "Motors",
  },
  {
    id: "20",
    name: "Breadboard Power Strip",
    description: "Power supply module for breadboards with 3.3V and 5V output.",
    price: 50,
    image: "/products/power-strip.jpg",
    category: "Power",
  },
  {
    id: "21",
    name: "600 RPM Johnson Grade A Motor",
    description: "High-speed 600 RPM DC motor for fast robots and spinning mechanisms.",
    price: 400,
    image: "/products/johnson-motor.jpg",
    category: "Motors",
  },
  {
    id: "22",
    name: "Arduino Uno",
    description: "The classic microcontroller board for beginners and pros alike.",
    price: 350,
    image: "/products/arduino-uno.jpg",
    category: "Microcontrollers",
  },
];
